let obj = {};
obj["AsyncOperation"] = ["callback","callbackObj","_itemList","_objectPool","_index","constructor","createObject","createObjectFromURL","cancel","internalCreateObject","collectComponentChildren","collectListChildren","run"];
obj["Controller"] = ["_selectedIndex","_previousIndex","_pageIds","_pageNames","_actions?","name","parent","autoRadioGroupDepth?","changing","constructor","dispose","selectedIndex","setSelectedIndex","readonlyprevisousIndex","selectedPage","setSelectedPage","readonlypreviousPage","readonlypageCount","getPageName","addPage","addPageAt","removePage","removePageAt","clearPages","hasPage","getPageIndexById","getPageIdByName","getPageNameById","getPageId","selectedPageId","oppositePageId","readonlypreviousPageId","runActions","setup"];
obj["DragDropManager"] = ["_agent","_sourceData","static_inst","staticreadonlyinst","constructor","readonlydragAgent","readonlydragging","startDrag","cancel","__dragEnd"];
obj["GObject"] = ["data","packageItem","staticdraggingObject","_x","_y","_alpha","_rotation","_visible","_touchable","_grayed","_draggable","_scaleX","_scaleY","_skewX","_skewY","_pivotX","_pivotY","_pivotAsAnchor","_pivotOffsetX","_pivotOffsetY","_sortingOrder","_internalVisible","_handlingController?","_tooltips?","_pixelSnapping?","_disposed?","_dragTesting?","_dragStartPos?","_relations","_group?","_gears","_displayObject","_dragBounds?","sourceWidth","sourceHeight","initWidth","initHeight","minWidth","minHeight","maxWidth","maxHeight","_parent","_width","_height","_rawWidth","_rawHeight","_id","_name","_underConstruct","_gearLocked?","_sizePercentInGroup","_treeNode?","staticXY_CHANGED","staticSIZE_CHANGED","staticSIZE_DELAY_CHANGE","staticGEAR_STOP","constructor","readonlyid","name","x","y","setXY","xMin","yMin","pixelSnapping","center","width","height","setSize","makeFullScreen","ensureSizeCorrect","readonlyactualWidth","readonlyactualHeight","scaleX","scaleY","setScale","skewX","skewY","setSkew","pivotX","pivotY","setPivot","readonlypivotAsAnchor","internalSetPivot","updatePivotOffset","applyPivot","touchable","grayed","enabled","rotation","readonlynormalizeRotation","alpha","visible","readonlyinternalVisible","readonlyinternalVisible2","readonlyinternalVisible3","sortingOrder","readonlyfocused","requestFocus","tooltips","blendMode","filters","readonlyinContainer","readonlyonStage","readonlyresourceURL","group","getGear","updateGear","checkGearController","updateGearFromRelations","addDisplayLock","releaseDisplayLock","checkGearDisplay","readonlygearXY","readonlygearSize","readonlygearLook","readonlyrelations","addRelation","removeRelation","readonlydisplayObject","setDisplayObject","parent","removeFromParent","readonlyroot","readonlyasCom","readonlyasButton","readonlyasLabel","readonlyasProgress","readonlyasTextField","readonlyasRichTextField","readonlyasTextInput","readonlyasLoader","readonlyasList","readonlyasTree","readonlyasGraph","readonlyasGroup","readonlyasSlider","readonlyasComboBox","readonlyasImage","readonlyasMovieClip","staticcast","text","icon","readonlyisDisposed","readonlytreeNode","dispose","addClickListener","removeClickListener","hasClickListener","addEventListener","removeEventListener","_reDispatch","draggable","dragBounds","startDrag","stopDrag","readonlydragging","localToGlobal","globalToLocal","localToRoot","rootToLocal","localToGlobalRect","globalToLocalRect","handleControllerChanged","createDisplayObject","switchDisplayObject","handleXYChanged","handleSizeChanged","handleScaleChanged","handleGrayedChanged","handleAlphaChanged","handleVisibleChanged","getProp","setProp","constructFromResource","setup_beforeAdd","setup_afterAdd","initDrag","dragBegin","dragEnd","reset","__begin","__moving","__end"];
obj["GComponent"] = ["_sortingChildCount","_applyingController?","_margin","_trackBounds","_boundsChanged","_childrenRenderOrder","_apexIndex","_buildingDisplayList","_children","_controllers","_transitions","_rootContainer","_container","_scrollPane?","_alignOffset","constructor","createDisplayObject","dispose","readonlydisplayListContainer","addChild","addChildAt","getInsertPosForSortingChild","removeChild","removeChildAt","removeChildren","getChildAt","getChild","getChildByPath","getVisibleChild","getChildInGroup","getChildById","getChildIndex","setChildIndex","setChildIndexBefore","_setChildIndex","swapChildren","swapChildrenAt","readonlynumChildren","isAncestorOf","addController","getControllerAt","getController","removeController","readonlycontrollers","childStateChanged","buildNativeDisplayList","applyController","applyAllControllers","adjustRadioGroupDepth","getTransitionAt","getTransition","isChildInView","getFirstChildInView","readonlyscrollPane","opaque","margin","childrenRenderOrder","apexIndex","mask","readonlybaseUserData","updateScrollRect","setupScroll","setupOverflow","handleSizeChanged","handleGrayedChanged","handleControllerChanged","setBoundsChangedFlag","__render","ensureBoundsCorrect","updateBounds","setBounds","viewWidth","viewHeight","getSnappingPosition","childSortingOrderChanged","constructFromResource","constructFromResource2","onConstruct","constructExtension","constructFromXML","setup_afterAdd","___added","___removed"];
obj["GButton"] = ["_titleObject","_iconObject","_mode","_selected","_title","_selectedTitle","_icon","_selectedIcon","_sound","_soundVolumeScale","_buttonController","_relatedController?","_relatedPageId","_changeStateOnClick","_linkedPopup?","_downEffect","_downEffectValue","_downScaled?","_down","_over","staticUP","staticDOWN","staticOVER","staticSELECTED_OVER","staticDISABLED","staticSELECTED_DISABLED","constructor","icon","selectedIcon","title","text","selectedTitle","titleColor","titleFontSize","sound","soundVolumeScale","selected","mode","relatedController","relatedPageId","changeStateOnClick","linkedPopup","getTextField","addStateListener","removeStateListener","fireClick","setState","handleControllerChanged","handleGrayedChanged","getProp","setProp","constructExtension","setup_afterAdd","__mousedown","__mouseup","__click"];
obj["GComboBox"] = ["dropdown","_titleObject","_iconObject","_list","_items","_values","_icons?","_visibleItemCount","_itemsUpdated","_selectedIndex","_buttonController","_popupDirection","_selectionController?","_over","_down","constructor","text","icon","titleColor","titleFontSize","visibleItemCount","popupDirection","items","icons","values","selectedIndex","value","selectionController","getTextField","setState","getProp","setProp","constructExtension","handleControllerChanged","updateSelectionController","dispose","setup_afterAdd","showDropdown","__popupWinClosed","__clickItem","__clickItem2","__mousedown","__mouseup"];
obj["GGraph"] = ["_graphics","_type","_lineSize","_lineColor","_lineAlpha","_fillColor","_fillAlpha","_cornerRadius?","_sides?","_startAngle?","_polygonPoints?","_distances?","constructor","readonlygraphics","drawRect","drawEllipse","drawRegularPolygon","drawPolygon","distances","clearGraphics","color","updateGraph","replaceMe","addBeforeMe","addAfterMe","setNativeObject","createDisplayObject","getProp","setProp","handleSizeChanged","setup_beforeAdd"];
obj["GGroup"] = ["_layout","_lineGap","_columnGap","_excludeInvisibles?","_autoSizeDisabled?","_mainGridIndex","_mainGridMinSize","_boundsChanged","_percentReady","_mainChildIndex","_totalSize","_numChildren","_updating","constructor","dispose","layout","lineGap","columnGap","excludeInvisibles","autoSizeDisabled","mainGridMinSize","mainGridIndex","setBoundsChangedFlag","ensureSizeCorrect","ensureBoundsCorrect","updateBounds","handleLayout","moveChildren","resizeChildren","handleAlphaChanged","handleVisibleChanged","setup_beforeAdd","setup_afterAdd"];
obj["GImage"] = ["_content","_flip","constructor","color","flip","fillMethod","fillOrigin","fillClockwise","fillAmount","texture","createDisplayObject","constructFromResource","handleXYChanged","getProp","setProp","setup_beforeAdd"];
obj["GLabel"] = ["_titleObject","_iconObject","constructor","icon","title","text","titleColor","titleFontSize","editable","getTextField","getProp","setProp","constructExtension","setup_afterAdd"];
obj["GList"] = ["itemRenderer","itemProvider","callbackThisObj","scrollItemToViewOnClick","foldInvisibleItems","_layout","_lineCount","_columnCount","_lineGap","_columnGap","_defaultItem","_autoResizeItem","_selectionMode","_align","_verticalAlign","_selectionController?","_lastSelectedIndex","_pool","_virtual?","_loop?","_numItems","_realNumItems","_firstIndex","_curLineItemCount","_curLineItemCount2","_itemSize?","_virtualListChanged","_virtualItems?","_eventLocked?","itemInfoVer","constructor","dispose","layout","lineCount","columnCount","lineGap","columnGap","align","verticalAlign","virtualItemSize","defaultItem","autoResizeItem","selectionMode","selectionController","readonlyitemPool","getFromPool","returnToPool","addChildAt","addItem","addItemFromPool","removeChildAt","removeChildToPoolAt","removeChildToPool","removeChildrenToPool","selectedIndex","getSelection","addSelection","removeSelection","clearSelection","clearSelectionExcept","selectAll","selectNone","selectReverse","handleArrowKey","__clickItem","dispatchItemEvent","setSelectionOnEvent","resizeToFit","getMaxItemWidth","handleSizeChanged","handleControllerChanged","updateSelectionController","getSnappingPosition","scrollToView","getFirstChildInView","childIndexToItemIndex","itemIndexToChildIndex","setVirtual","setVirtualAndLoop","_setVirtual","numItems","refreshVirtualList","checkVirtualList","setVirtualListChangedFlag","_refreshVirtualList","__scrolled","getIndexOnPos1","getIndexOnPos2","getIndexOnPos3","handleScroll","handleScroll1","handleScroll2","handleScroll3","handleArchOrder1","handleArchOrder2","handleAlign","updateBounds","setup_beforeAdd","readItems","setupItem","setup_afterAdd"];
obj["GObjectPool"] = ["_pool","_count","constructor","clear","readonlycount","getObject","returnObject"];
obj["GLoader"] = ["_url","_align","_verticalAlign","_autoSize","_fill","_shrinkOnly","_showErrorSign","_contentItem","_container","_content","_errorSign?","_content2?","_updatingLayout","static_errorSignPool","constructor","createDisplayObject","dispose","url","icon","align","verticalAlign","fill","shrinkOnly","autoSize","playing","frame","color","showErrorSign","readonlycontent","readonlycomponent","texture","fillMethod","fillOrigin","fillClockwise","fillAmount","loadContent","loadFromPackage","loadExternal","freeExternal","onExternalLoadSuccess","onExternalLoadFailed","__getResCompleted","setErrorState","clearErrorState","updateLayout","clearContent","handleSizeChanged","getProp","setProp","setup_beforeAdd"];
obj["GLoader3D"] = ["_url","_align","_verticalAlign","_autoSize","_fill","_shrinkOnly","_playing","_frame","_loop","_animationName","_skinName","_color","_contentItem","_container","_content","_updatingLayout","constructor","createDisplayObject","dispose","url","icon","align","verticalAlign","fill","shrinkOnly","autoSize","playing","frame","animationName","skinName","loop","color","readonlycontent","loadContent","loadFromPackage","onLoaded","setDragonBones","onChange","onChangeDragonBones","loadExternal","updateLayout","clearContent","handleSizeChanged","handleGrayedChanged","getProp","setProp","setup_beforeAdd"];
obj["GMovieClip"] = ["_content","constructor","color","createDisplayObject","playing","frame","timeScale","rewind","syncStatus","advance","setPlaySettings","getProp","setProp","constructFromResource","setup_beforeAdd"];
obj["GProgressBar"] = ["_min","_max","_value","_titleType","_reverse","_titleObject","_aniObject","_barObjectH","_barObjectV","_barMaxWidth","_barMaxHeight","_barMaxWidthDelta","_barMaxHeightDelta","_barStartX","_barStartY","constructor","titleType","min","max","value","tweenValue","update","setFillAmount","constructExtension","handleSizeChanged","setup_afterAdd"];
obj["GTextField"] = ["_textField","_bitmapContainer?","_font","_fontSize","_align","_verticalAlign","_color","_leading","_letterSpacing","_underline","_text","_ubbEnabled","_templateVars?","[index"];
obj["GRichTextField"] = ["constructor","updateTextFieldText"];
obj["GRoot"] = ["staticcontentScaleLevel","_nativeStage","_modalLayer","_popupStack","_justClosedPopups","_modalWaitPane","_tooltipWin","_defaultTooltipWin","_volumeScale","static_inst","statictouchScreen","staticcontentScaleFactor","statictouchDown","staticctrlKeyDown","staticshiftKeyDown","staticmouseX","staticmouseY","staticreadonlyinst","constructor","readonlynativeStage","showWindow","hideWindow","hideWindowImmediately","bringToFront","showModalWait","closeModalWait","closeAllExceptModals","closeAllWindows","getTopWindow","readonlymodalLayer","readonlyhasModalWindow","readonlymodalWaiting","showPopup","togglePopup","hidePopup","readonlyhasAnyPopup","closePopup","showTooltips","showTooltipsWin","hideTooltips","getObjectUnderPoint","focus","setFocus","volumeScale","playOneShotSound","adjustModalLayer","__addedToStage","__stageMouseDownCapture","__stageMouseMoveCapture","__stageMouseUpCapture","__winResize","updateContentScaleLevel"];
obj["GScrollBar"] = ["_grip","_arrowButton1","_arrowButton2","_bar","_target","_vertical","_scrollPerc","_fixedGripSize","_dragOffset","_gripDragging","constructor","setScrollPane","setDisplayPerc","setScrollPerc","readonlyminSize","readonlygripDragging","constructExtension","__gripMouseDown","__gripMouseMove","__gripMouseUp","__arrowButton1Click","__arrowButton2Click","__barMouseDown"];
obj["GSlider"] = ["_min","_max","_value","_titleType","_reverse","_wholeNumbers","_titleObject","_barObjectH","_barObjectV","_barMaxWidth","_barMaxHeight","_barMaxWidthDelta","_barMaxHeightDelta","_gripObject","_clickPos","_clickPercent","_barStartX","_barStartY","changeOnClick","canDrag","constructor","titleType","wholeNumbers","min","max","value","update","updateWithPercent","constructExtension","handleSizeChanged","setup_afterAdd","__gripMouseDown","__gripMouseMove","__gripMouseUp","__barMouseDown"];
obj["GTextInput"] = ["_promptText","_password","constructor","dispose","editable","maxLength","promptText","restrict","password","verticalAlign","updateVertAlign","updateTextFieldText","handleSizeChanged","setup_beforeAdd","setup_afterAdd","__textChanged","__focusIn","__focusOut"];
obj["GTree"] = ["treeNodeRender","treeNodeWillExpand","_indent","_clickToExpand","_rootNode","_expandedStatusInEvt","constructor","readonlyrootNode","indent","clickToExpand","getSelectedNode","getSelectedNodes","selectNode","unselectNode","expandAll","collapseAll","createCell","_afterInserted","getInsertIndexForNode","_afterRemoved","_afterExpanded","_afterCollapsed","_afterMoved","getFolderEndIndex","checkChildren","hideFolderNode","removeNode","__cellMouseDown","__expandedStateChanged","dispatchItemEvent","setup_beforeAdd","readItems"];
obj["GTreeNode"] = ["data","_parent","_children","_expanded","_level","_tree","_cell","_resURL?","constructor","expanded","readonlyisFolder","readonlyparent","text","icon","readonlycell","readonlylevel","_setLevel","addChild","addChildAt","removeChild","removeChildAt","removeChildren","getChildAt","getChildIndex","getPrevSibling","getNextSibling","setChildIndex","swapChildren","swapChildrenAt","readonlynumChildren","expandToRoot","readonlytree","_setTree"];
obj["Margin"] = ["left","right","top","bottom","constructor","copy"];
obj["PixelHitTest"] = ["_data","offsetX","offsetY","scaleX","scaleY","constructor","contains"];
obj["PixelHitTestData"] = ["pixelWidth","scale","pixels","constructor","load"];
obj["PackageItem"] = ["owner","type","objectType?","id","name","width","height","file","decoded?","loading?","rawData?","asset?","highResolution?","branches?","scale9Grid?","scaleByTile?","tileGridIndice?","smoothing?","pixelHitTestData?","interval?","repeatDelay?","swing?","frames?","extensionType?","bitmapFont?","skeletonAnchor?","armatureName?","constructor","load","getBranch","getHighResolution","toString"];
obj["PopupMenu"] = ["_contentPane","_list","constructor","dispose","addItem","addItemAt","addSeperator","getItemName","setItemText","setItemVisible","setItemGrayed","setItemCheckable","setItemChecked","isItemChecked","removeItem","clearItems","readonlyitemCount","readonlycontentPane","readonlylist","show","__clickItem","__clickItem2","__addedToStage"];
obj["RelationItem"] = ["_owner","_target","_defs","_targetX","_targetY","_targetWidth","_targetHeight","constructor","readonlyowner","target","add","internalAdd","remove","copyFrom","dispose","readonlyisEmpty","applyOnSelfResized","applyOnXYChanged","applyOnSizeChanged","addRefTarget","releaseRefTarget","__targetXYChanged","__targetSizeChanged","__targetSizeWillChange"];
obj["RelationDef"] = ["percent","type","axis","constructor","copyFrom"];
obj["Relations"] = ["_owner","_items","handling","sizeDirty","constructor","add","remove","contains","clearFor","clearAll","copyFrom","dispose","onOwnerSizeChanged","ensureRelationsSizeCorrect","readonlyempty","setup"];
obj["ScrollPane"] = ["_owner","_container","_maskContainer","_alignContainer?","_scrollType","_scrollStep","_decelerationRate","_scrollBarMargin","_bouncebackEffect","_touchEffect","_scrollBarDisplayAuto?","_vScrollNone","_hScrollNone","_needRefresh","_refreshBarAxis","_displayOnLeft?","_snapToItem?","_displayInDemand?","_pageMode?","_inertiaDisabled?","_floating?","_dontClipMargin?","_xPos","_yPos","_viewSize","_contentSize","_overlapSize","_pageSize","_containerPos","_beginTouchPos","_lastTouchPos","_lastTouchGlobalPos","_velocity","_velocityScale","_lastMoveTime","_isHoldAreaDone","_aniFlag","_loop","_headerLockedSize","_footerLockedSize","_refreshEventDispatching","_dragged","_tweening","_tweenTime","_tweenDuration","_tweenStart","_tweenChange","_pageController?","_hzScrollBar?","_vtScrollBar?","_header?","_footer?","staticdraggingPane","staticSCROLL","staticSCROLL_END","staticPULL_DOWN_RELEASE","staticPULL_UP_RELEASE","constructor","setup","dispose","readonlyowner","readonlyhzScrollBar","readonlyvtScrollBar","readonlyheader","readonlyfooter","bouncebackEffect","touchEffect","scrollStep","decelerationRate","snapToItem","readonlyisDragged","percX","setPercX","percY","setPercY","posX","setPosX","posY","setPosY","readonlycontentWidth","readonlycontentHeight","viewWidth","viewHeight","currentPageX","currentPageY","setCurrentPageX","setCurrentPageY","readonlyisBottomMost","readonlyisRightMost","pageController","readonlyscrollingPosX","readonlyscrollingPosY","scrollTop","scrollBottom","scrollUp","scrollDown","scrollLeft","scrollRight","scrollToView","isChildInView","cancelDragging","lockHeader","lockFooter","onOwnerSizeChanged","handleControllerChanged","updatePageController","adjustMaskContainer","setSize","setContentSize","changeContentSizeOnScrolling","handleSizeChanged","posChanged","refresh","refresh2","__touchBegin","__touchMove","__touchEnd","__touchTap","updateScrollBarPos","updateScrollBarVisible","updateScrollBarVisible2","__barTweenComplete","getLoopPartSize","loopCheckingCurrent","loopCheckingTarget","loopCheckingTarget2","loopCheckingNewPos","alignPosition","alignByPage","updateTargetAndDuration","updateTargetAndDuration2","fixDuration","startTween","killTween","checkRefreshBar","tweenUpdate","runTween"];
obj["Transition"] = ["name","_owner","_ownerBaseX","_ownerBaseY","_items","_totalTimes","_totalTasks","_playing","_paused","_onComplete","_onCompleteCaller","_onCompleteParam","_options","_reversed","_totalDuration","_autoPlay","_autoPlayTimes","_autoPlayDelay","_timeScale","_startTime","_endTime","constructor","play","playReverse","changePlayTimes","setAutoPlay","_play","stop","stopItem","setPaused","dispose","readonlyplaying","setValue","setHook","clearHooks","setTarget","setDuration","getLabelTime","timeScale","updateFromRelations","onOwnerAddedToStage","onOwnerRemovedFromStage","onDelayedPlay","internalPlay","playItem","skipAnimations","onDelayedPlayItem","onTweenStart","onTweenUpdate","onTweenComplete","onPlayTransCompleted","callHook","checkAllComplete","applyValue","setup","decodeValue"];
obj["TranslationHelper"] = ["staticstrings","[index","[index"];
obj["UIConfig"] = ["constructor","staticdefaultFont","staticwindowModalWaiting","staticglobalModalWaiting","staticmodalLayerColor","staticmodalLayerAlpha","staticbuttonSound","staticbuttonSoundVolumeScale","statichorizontalScrollBar","staticverticalScrollBar","staticdefaultScrollStep","staticdefaultScrollDecelerationRate","staticdefaultScrollBarDisplay","staticdefaultScrollTouchEffect","staticdefaultScrollBounceEffect","staticpopupMenu","staticpopupMenu_seperator","staticloaderErrorSign","statictooltipsWin","staticdefaultComboBoxVisibleItemCount","statictouchScrollSensitivity","statictouchDragSensitivity","staticclickDragSensitivity","staticbringWindowToFrontOnClick","staticframeTimeForAsyncUIConstruction"];
obj["UIObjectFactory"] = ["staticextensions","[index"];
obj["UIPackage"] = ["_id","_name","_items","_itemsById","_itemsByName","_resKey","_customId","_sprites","_dependencies","_branches","_branchIndex","static_constructing","static_instById","static_instByName","static_branch","static_vars","constructor","staticbranch","staticgetVar","staticsetVar","staticgetById","staticgetByName","staticloadPackage","staticaddPackage","staticremovePackage","staticcreateObject","staticcreateObjectFromURL","staticgetItemURL","staticgetItemByURL","staticnormalizeURL","staticsetStringsSource","loadPackage","dispose","readonlyid","readonlyname","customId","createObject","internalCreateObject","getItemById","getItemByName","getItemAssetByName","getItemAsset","getItemAssetAsync","loadMovieClip","loadFont","loadDragonBones"];
obj["Window"] = ["_contentPane","_modalWaitPane","_closeButton","_dragArea","_contentArea","_frame","_modal","_uiSources?","_inited?","_loading?","_requestingCmd","bringToFontOnClick","constructor","addUISource","contentPane","readonlyframe","closeButton","dragArea","contentArea","show","showOn","hide","hideImmediately","centerOn","toggleStatus","readonlyisShowing","readonlyisTop","modal","bringToFront","showModalWait","layoutModalWaitPane","closeModalWait","readonlymodalWaiting","init","onInit","onShown","onHide","doShowAnimation","doHideAnimation","__uiLoadComplete","_init","dispose","closeEventHandler","__onShown","__onHidden","__mouseDown","__dragStart"];
obj["ControllerAction"] = ["fromPage","toPage","staticcreateAction","constructor","run","enter","leave","setup"];
obj["ChangePageAction"] = ["objectId","controllerName","targetPage","constructor","enter","setup"];
obj["PlayTransitionAction"] = ["transitionName","playTimes","delay","stopOnExit","_currentTransition","constructor","enter","leave","setup"];
obj["BitmapFont"] = ["id","size","ttf","glyphs","[index"];
obj["Image"] = ["_fillMethod","_fillOrigin","_fillAmount","_fillClockwise?","_mask?","_maskDirtyFlag?","_color","constructor","color","$setX","$setY","fillMethod","fillOrigin","fillClockwise","fillAmount","markChanged","doFill"];
obj["MovieClip"] = ["interval","swing","repeatDelay","timeScale","_playing","_frameCount","_frames","_frame","_start","_end","_times","_endAt","_status","_callback","_callbackObj","_smoothing","_frameElapsed","_reversed","_repeatedCount","constructor","frames","readonlyframeCount","frame","playing","smoothing","rewind","syncStatus","advance","setPlaySettings","update","drawFrame","checkTimer","$onAddToStage","$onRemoveFromStage"];
obj["UIContainer"] = ["_hitArea?","_cachedMatrix?","_cachedHitArea?","_opaque?","constructor","cacheHitArea","hitArea","opaque","$hitTest"];
obj["DragEvent"] = ["stageX","stageY","touchPointID","_prevented","staticDRAG_START","staticDRAG_END","staticDRAG_MOVING","constructor","preventDefault","isDefaultPrevented"];
obj["DropEvent"] = ["source","staticDROP","constructor"];
obj["ItemEvent"] = ["itemObject","stageX","stageY","staticCLICK","constructor"];
obj["StateChangeEvent"] = ["staticCHANGED","constructor"];
obj["GearBase"] = ["staticdisableAllTweenEffect","_owner","_controller","_tweenConfig?","staticcreate","constructor","dispose","controller","readonlytweenConfig","setup","updateFromRelations","addStatus","init","apply","updateState"];
obj["GearTweenConfig"] = ["tween","easeType","duration","delay","_displayLockToken","_tweener","constructor"];
obj["GearAnimation"] = ["_storage","_default","constructor","init","addStatus","apply","updateState"];
obj["GearColor"] = ["_storage","_default","constructor","init","addStatus","apply","updateState"];
obj["GearDisplay"] = ["pages","_visible","_displayLockToken","constructor","init","apply","addLock","releaseLock","readonlyconnected"];
obj["GearDisplay2"] = ["pages","condition","_visible","constructor","init","apply","evaluate"];
obj["GearFontSize"] = ["_storage","_default","constructor","init","addStatus","apply","updateState"];
obj["GearIcon"] = ["_storage","_default","constructor","init","addStatus","apply","updateState"];
obj["GearLook"] = ["_storage","_default","constructor","init","addStatus","apply","__tweenUpdate","__tweenComplete","updateState"];
obj["GearSize"] = ["_storage","_default","constructor","init","addStatus","apply","__tweenUpdate","__tweenComplete","updateState","updateFromRelations"];
obj["GearText"] = ["_storage","_default","constructor","init","addStatus","apply","updateState"];
obj["GearXY"] = ["positionsInPercent","_storage","_default","constructor","init","addStatus","addExtStatus","apply","__tweenUpdate","__tweenComplete","updateState","updateFromRelations"];
obj["EaseType"] = ["staticLinear","staticSineIn","staticSineOut","staticSineInOut","staticQuadIn","staticQuadOut","staticQuadInOut","staticCubicIn","staticCubicOut","staticCubicInOut","staticQuartIn","staticQuartOut","staticQuartInOut","staticQuintIn","staticQuintOut","staticQuintInOut","staticExpoIn","staticExpoOut","staticExpoInOut","staticCircIn","staticCircOut","staticCircInOut","staticElasticIn","staticElasticOut","staticElasticInOut","staticBackIn","staticBackOut","staticBackInOut","staticBounceIn","staticBounceOut","staticBounceInOut","staticCustom"];
obj["GPath"] = ["_segments","_points","_fullLength","constructor","readonlylength","create","createSplineSegment","clear","getPointAt","readonlysegmentCount","getAnchorsInSegment","getPointsInSegment","getAllPoints","onCRSplineCurve","onBezierCurve"];
obj["GPathPoint"] = ["x","y","control1_x","control1_y","control2_x","control2_y","curveType","constructor","staticnewPoint","staticnewBezierPoint","staticnewCubicBezierPoint","clone"];
obj["GTween"] = ["staticcatchCallbackExceptions","staticto","staticto2","staticto3","staticto4","statictoColor","staticdelayedCall","staticshake","staticisTweening","statickill","staticgetTween"];
obj["GTweener"] = ["_target","_propType","_killed","_paused","_delay","_duration","_breakpoint","_easeType","_easeOvershootOrAmplitude","_easePeriod","_repeat","_yoyo","_timeScale","_snapping","_userData","_path","_onUpdate","_onStart","_onComplete","_onUpdateCaller","_onStartCaller","_onCompleteCaller","_startValue","_endValue","_value","_deltaValue","_valueSize","_started","_ended","_elapsedTime","_normalizedTime","constructor","setDelay","readonlydelay","setDuration","readonlyduration","setBreakpoint","setEase","setEasePeriod","setEaseOvershootOrAmplitude","setRepeat","readonlyrepeat","setTimeScale","setSnapping","setTarget","readonlytarget","setUserData","readonlyuserData","setPath","onUpdate","onStart","onComplete","readonlystartValue","readonlyendValue","readonlyvalue","readonlydeltaValue","readonlynormalizedTime","readonlycompleted","readonlyallCompleted","setPaused","seek","kill","_to","_to2","_to3","_to4","_toColor","_shake","_init","_reset","_update","update","callStartCallback","callUpdateCallback","callCompleteCallback"];
obj["TweenManager"] = ["staticcreateTween","staticisTweening","statickillTweens","staticgetTween","staticupdate"];
obj["TweenValue"] = ["x","y","z","w","constructor","color","getField","setField","setZero"];
obj["ByteBuffer"] = ["stringTable?","version","constructor","skip","readBool","readS","readSArray","writeS","readColor","readChar","readBuffer","seek"];
obj["ColorMatrix"] = ["readonlymatrix","constructor","reset","invert","adjustColor","adjustBrightness","adjustContrast","adjustSaturation","adjustHue","concat","clone","copyMatrix","multiplyMatrix","cleanValue"];
obj["GTimers"] = ["_items","_itemPool","_enumI","_enumCount","_lastTime","staticdeltaTime","statictime","staticreadonlyinst","constructor","getItem","findItem","add","callLater","callDelay","exists","remove","__timer"];
obj["UBBParser"] = ["_text","_readPos","_handlers","[index"];
obj["ToolSet"] = ["staticstartsWith","statictrimRight","staticconvertToHtmlColor","staticconvertFromHtmlColor","staticdisplayObjectToGObject","staticencodeHTML","staticclamp","staticclamp01","staticlerp","staticrepeat","staticdistance","staticfillPath","staticsetColorFilter"];

/**
 * 过滤与基础组件重复的变量
 * @param clsName 
 * @param varName 
 * @returns false 不用过滤    true 需要过滤
 */
export function filterInnerVars(clsName:string, varName:string){
    clsName = clsName.replace("fgui.","")
    if(!obj[clsName])return false;
    return obj[clsName].indexOf(varName) != -1;
}